### ISSUE TITLE
EAX sound installable

### ISSUE THREAD

**Issue by SubhadeepJasu** [yumiris/spv3-promise#1]
dsound.dll and dsound.ini should be installable or uninstallable from the launcher.

**Comment by yumiris** [comment]
Well, question is where and why should they be installed? Game directory, or..?

**Comment by SubhadeepJasu** [comment]
They should be installed in the spv3 folder where the 'haloce.exe' is located. These files enhance the sound quality of the engine by enabling EAX (Environmental Audio Extensions). Only known issue is occasional crashes in some parts of the campaign with heavy use of sound effects. However this may also occur due to hardware limitations. The Users would need to be given a choice to use this extension. But in case of crashes they may choose to uninstall the extension from the launcher. This extension is not installed by default and has to be installed manually from the launcher. After installation of the extension, the user has to enable hardware acceleration and EAX from the in-game UI.

**Comment by yumiris** [comment]
That can be implemented. Do you think the users should be prompted to install it when starting up the game for the very first time?

**Comment by SubhadeepJasu** [comment]
That would be better, because most players won't know about this feature.

**Comment by yumiris** [comment]
Will be implemented in the upcoming release. Mind providing the two respective files? Cheers!
